### ISSUE TITLE
500 SERVER ERROR

### ISSUE THREAD

**Issue by andrelmariano** [PritamNandy/whatsapp_redirector#1]
![image](https://user-images.githubusercontent.com/4019432/127495778-dd645996-aec4-480b-8d67-87f5de70fd9f.png)

does not appear as campaigns or the side menu, help me?

**Comment by PritamNandy** [comment]
Hey @andrelmariano. Pull updated code from repo. I already tested it. Sidebar is working.

**Comment by PritamNandy** [comment]
Also check the AuthServiceProvider.php. If the gates are introduced properly or not.
